export const images = {
    main: require("./images/main.png"),
    first: require("./images/first.png"),
    badge:require("./images/badge.png"),
    play: require("./images/play.png"),
    john: require("./images/john.png"),
    breakfast: require("./images/breakfast.png"),
    vegan: require("./images/vegan.png"),
    meat: require("./images/meat.png"),
    desert: require("./images/desert.png"),
    lunch: require("./images/lunch.png"),
    chocolate: require("./images/chocolate.png"),
    cheeseburger: require("./images/cheeseburger.png"),
    ginger: require("./images/ginger.png"),
    honey: require("./images/honey.png"),
    salad: require("./images/salad.png"),
    meatballs: require("./images/meatballs.png"),
    ads: require("./images/ads.png"),
    pancake: require("./images/pancake.png"),
    chicken: require("./images/chicken.png"),
    pasta: require("./images/pasta.png"),
    chef: require("./images/chef.png"),
    post: require("./images/post.png"),
    post2: require("./images/post2.png"),
    post3: require("./images/post3.png"),
    post4: require("./images/post4.png"),
    fruitsalad: require("./images/fruitsalad.png"),
    beef: require("./images/beef.png"),
    rice: require("./images/rice.png"),
    taco: require("./images/taco.png"),
    mustard: require("./images/mustard.png"),
    barbeque: require("./images/barbeque.png"),
    spicy: require("./images/spicy.png"),
    mushroom: require("./images/mushroom.png"),
    bg1: require("./images/bg1.png"),
    bg4: require("./images/bg4.png"),
    bg3: require("./images/bg3.png")



};